blank_issues_enabled: false
contact_links:
  - name: Suggesting Ideas | 💡
    url: https://github.com/melontini/blame-log/discussions/categories/ideas
    about: If you have a suggestion, please post it here.
