name: Crash Report
description: File a crash report
title: "[Crash]: "
labels: ["crash"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this crash report!
        Before proceeding, please make sure to do this first. 📋
        - Ensure you are running the **latest** version of the mod.
        - A similar report hasn't been filled before.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please explain in detail how this crash happened.
    validations:
      required: true
  - type: input
    attributes:
      label: Logs
      description: |
        `latest.log` or `crash-20xx-xx-xx_xx.xx.xx-(client/server).log`.
        Please upload your log to [Github Gist](https://gist.github.com/), [mslo.gs](https://mclo.gs/) or any other pasting platform.
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Mod Version
      description: What version of the mod are you running?
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running?
    validations:
      required: true
